apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: test-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: stable.example.com/v1
    resource: mycustomresources
  childResources:
  - apiVersion: v1
    resource: pods
    updateStrategy:
      method: Recreate
  - apiVersion: v1
    resource: pods
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://test-controller.namespacea/sync
    finalize:
      webhook:
        url: http://test-controller.namespacea/sync
