apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mycustomresources.stable.example.com
spec:
  group: stable.example.com
  names:
    kind: MyCustomResource
    plural: mycustomresources
    singular: mycustomresource
    shortNames:
    - mcr
  scope: Namespaced
  version: v1
  validation:
    openAPIV3Schema:
      required: ["spec", "status"]
      properties:
        spec:
          required: ["state"]
          properties:
            state:
              type: string    
        status:
          required: ["phase"]
          properties:
            state:
              type: string    
                